/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ByteCode {
  #[serde(rename = "bytecode")]
  bytecode: String
}

impl ByteCode {
  pub fn new(bytecode: String) -> ByteCode {
    ByteCode {
      bytecode: bytecode
    }
  }

  pub fn set_bytecode(&mut self, bytecode: String) {
    self.bytecode = bytecode;
  }

  pub fn with_bytecode(mut self, bytecode: String) -> ByteCode {
    self.bytecode = bytecode;
    self
  }

  pub fn bytecode(&self) -> &String {
    &self.bytecode
  }


}



