/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Calldata {
  #[serde(rename = "calldata")]
  calldata: ::models::EncodedByteArray
}

impl Calldata {
  pub fn new(calldata: ::models::EncodedByteArray) -> Calldata {
    Calldata {
      calldata: calldata
    }
  }

  pub fn set_calldata(&mut self, calldata: ::models::EncodedByteArray) {
    self.calldata = calldata;
  }

  pub fn with_calldata(mut self, calldata: ::models::EncodedByteArray) -> Calldata {
    self.calldata = calldata;
    self
  }

  pub fn calldata(&self) -> &::models::EncodedByteArray {
    &self.calldata
  }


}



