/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChannelForceProgressTx {
  #[serde(rename = "channel_id")]
  channel_id: ::models::EncodedHash,
  #[serde(rename = "from_id")]
  from_id: ::models::EncodedHash,
  #[serde(rename = "payload")]
  payload: String,
  /// Channel's next round
  #[serde(rename = "round")]
  round: i64,
  /// Update to be applied. Must be a OffChainCallContract
  #[serde(rename = "update")]
  update: ::models::OffChainUpdate,
  /// Channel's next state_hash
  #[serde(rename = "state_hash")]
  state_hash: ::models::EncodedHash,
  #[serde(rename = "ttl")]
  ttl: Option<i64>,
  #[serde(rename = "fee")]
  fee: i64,
  #[serde(rename = "nonce")]
  nonce: Option<i64>,
  /// The whole set of off-chain state trees
  #[serde(rename = "offchain_trees")]
  offchain_trees: Option<::models::EncodedHash>
}

impl ChannelForceProgressTx {
  pub fn new(channel_id: ::models::EncodedHash, from_id: ::models::EncodedHash, payload: String, round: i64, update: ::models::OffChainUpdate, state_hash: ::models::EncodedHash, fee: i64) -> ChannelForceProgressTx {
    ChannelForceProgressTx {
      channel_id: channel_id,
      from_id: from_id,
      payload: payload,
      round: round,
      update: update,
      state_hash: state_hash,
      ttl: None,
      fee: fee,
      nonce: None,
      offchain_trees: None
    }
  }

  pub fn set_channel_id(&mut self, channel_id: ::models::EncodedHash) {
    self.channel_id = channel_id;
  }

  pub fn with_channel_id(mut self, channel_id: ::models::EncodedHash) -> ChannelForceProgressTx {
    self.channel_id = channel_id;
    self
  }

  pub fn channel_id(&self) -> &::models::EncodedHash {
    &self.channel_id
  }


  pub fn set_from_id(&mut self, from_id: ::models::EncodedHash) {
    self.from_id = from_id;
  }

  pub fn with_from_id(mut self, from_id: ::models::EncodedHash) -> ChannelForceProgressTx {
    self.from_id = from_id;
    self
  }

  pub fn from_id(&self) -> &::models::EncodedHash {
    &self.from_id
  }


  pub fn set_payload(&mut self, payload: String) {
    self.payload = payload;
  }

  pub fn with_payload(mut self, payload: String) -> ChannelForceProgressTx {
    self.payload = payload;
    self
  }

  pub fn payload(&self) -> &String {
    &self.payload
  }


  pub fn set_round(&mut self, round: i64) {
    self.round = round;
  }

  pub fn with_round(mut self, round: i64) -> ChannelForceProgressTx {
    self.round = round;
    self
  }

  pub fn round(&self) -> &i64 {
    &self.round
  }


  pub fn set_update(&mut self, update: ::models::OffChainUpdate) {
    self.update = update;
  }

  pub fn with_update(mut self, update: ::models::OffChainUpdate) -> ChannelForceProgressTx {
    self.update = update;
    self
  }

  pub fn update(&self) -> &::models::OffChainUpdate {
    &self.update
  }


  pub fn set_state_hash(&mut self, state_hash: ::models::EncodedHash) {
    self.state_hash = state_hash;
  }

  pub fn with_state_hash(mut self, state_hash: ::models::EncodedHash) -> ChannelForceProgressTx {
    self.state_hash = state_hash;
    self
  }

  pub fn state_hash(&self) -> &::models::EncodedHash {
    &self.state_hash
  }


  pub fn set_ttl(&mut self, ttl: i64) {
    self.ttl = Some(ttl);
  }

  pub fn with_ttl(mut self, ttl: i64) -> ChannelForceProgressTx {
    self.ttl = Some(ttl);
    self
  }

  pub fn ttl(&self) -> Option<&i64> {
    self.ttl.as_ref()
  }

  pub fn reset_ttl(&mut self) {
    self.ttl = None;
  }

  pub fn set_fee(&mut self, fee: i64) {
    self.fee = fee;
  }

  pub fn with_fee(mut self, fee: i64) -> ChannelForceProgressTx {
    self.fee = fee;
    self
  }

  pub fn fee(&self) -> &i64 {
    &self.fee
  }


  pub fn set_nonce(&mut self, nonce: i64) {
    self.nonce = Some(nonce);
  }

  pub fn with_nonce(mut self, nonce: i64) -> ChannelForceProgressTx {
    self.nonce = Some(nonce);
    self
  }

  pub fn nonce(&self) -> Option<&i64> {
    self.nonce.as_ref()
  }

  pub fn reset_nonce(&mut self) {
    self.nonce = None;
  }

  pub fn set_offchain_trees(&mut self, offchain_trees: ::models::EncodedHash) {
    self.offchain_trees = Some(offchain_trees);
  }

  pub fn with_offchain_trees(mut self, offchain_trees: ::models::EncodedHash) -> ChannelForceProgressTx {
    self.offchain_trees = Some(offchain_trees);
    self
  }

  pub fn offchain_trees(&self) -> Option<&::models::EncodedHash> {
    self.offchain_trees.as_ref()
  }

  pub fn reset_offchain_trees(&mut self) {
    self.offchain_trees = None;
  }

}



