/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ContractStore {
  #[serde(rename = "store")]
  store: Vec<::models::ContractStoreStore>
}

impl ContractStore {
  pub fn new(store: Vec<::models::ContractStoreStore>) -> ContractStore {
    ContractStore {
      store: store
    }
  }

  pub fn set_store(&mut self, store: Vec<::models::ContractStoreStore>) {
    self.store = store;
  }

  pub fn with_store(mut self, store: Vec<::models::ContractStoreStore>) -> ContractStore {
    self.store = store;
    self
  }

  pub fn store(&self) -> &Vec<::models::ContractStoreStore> {
    &self.store
  }


}



