/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Error {
  #[serde(rename = "reason")]
  reason: String
}

impl Error {
  pub fn new(reason: String) -> Error {
    Error {
      reason: reason
    }
  }

  pub fn set_reason(&mut self, reason: String) {
    self.reason = reason;
  }

  pub fn with_reason(mut self, reason: String) -> Error {
    self.reason = reason;
    self
  }

  pub fn reason(&self) -> &String {
    &self.reason
  }


}



