/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2003 {
  #[serde(rename = "pubkey")]
  pubkey: Option<String>
}

impl InlineResponse2003 {
  pub fn new() -> InlineResponse2003 {
    InlineResponse2003 {
      pubkey: None
    }
  }

  pub fn set_pubkey(&mut self, pubkey: String) {
    self.pubkey = Some(pubkey);
  }

  pub fn with_pubkey(mut self, pubkey: String) -> InlineResponse2003 {
    self.pubkey = Some(pubkey);
    self
  }

  pub fn pubkey(&self) -> Option<&String> {
    self.pubkey.as_ref()
  }

  pub fn reset_pubkey(&mut self) {
    self.pubkey = None;
  }

}



