/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NameHash {
  #[serde(rename = "name_id")]
  name_id: ::models::EncodedHash
}

impl NameHash {
  pub fn new(name_id: ::models::EncodedHash) -> NameHash {
    NameHash {
      name_id: name_id
    }
  }

  pub fn set_name_id(&mut self, name_id: ::models::EncodedHash) {
    self.name_id = name_id;
  }

  pub fn with_name_id(mut self, name_id: ::models::EncodedHash) -> NameHash {
    self.name_id = name_id;
    self
  }

  pub fn name_id(&self) -> &::models::EncodedHash {
    &self.name_id
  }


}



