/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OffChainWithdrawal {
  #[serde(rename = "op")]
  op: String,
  /// Withdrawer of tokens
  #[serde(rename = "to")]
  to: ::models::EncodedHash,
  /// Amount of tokens to withdraw
  #[serde(rename = "am")]
  am: i64
}

impl OffChainWithdrawal {
  pub fn new(op: String, to: ::models::EncodedHash, am: i64) -> OffChainWithdrawal {
    OffChainWithdrawal {
      op: op,
      to: to,
      am: am
    }
  }

  pub fn set_op(&mut self, op: String) {
    self.op = op;
  }

  pub fn with_op(mut self, op: String) -> OffChainWithdrawal {
    self.op = op;
    self
  }

  pub fn op(&self) -> &String {
    &self.op
  }


  pub fn set_to(&mut self, to: ::models::EncodedHash) {
    self.to = to;
  }

  pub fn with_to(mut self, to: ::models::EncodedHash) -> OffChainWithdrawal {
    self.to = to;
    self
  }

  pub fn to(&self) -> &::models::EncodedHash {
    &self.to
  }


  pub fn set_am(&mut self, am: i64) {
    self.am = am;
  }

  pub fn with_am(mut self, am: i64) -> OffChainWithdrawal {
    self.am = am;
    self
  }

  pub fn am(&self) -> &i64 {
    &self.am
  }


}



