/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OracleQueries {
  #[serde(rename = "oracle_queries")]
  oracle_queries: Vec<::models::OracleQuery>
}

impl OracleQueries {
  pub fn new(oracle_queries: Vec<::models::OracleQuery>) -> OracleQueries {
    OracleQueries {
      oracle_queries: oracle_queries
    }
  }

  pub fn set_oracle_queries(&mut self, oracle_queries: Vec<::models::OracleQuery>) {
    self.oracle_queries = oracle_queries;
  }

  pub fn with_oracle_queries(mut self, oracle_queries: Vec<::models::OracleQuery>) -> OracleQueries {
    self.oracle_queries = oracle_queries;
    self
  }

  pub fn oracle_queries(&self) -> &Vec<::models::OracleQuery> {
    &self.oracle_queries
  }


}



