/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PoI {
  /// Proof of inclusion
  #[serde(rename = "poi")]
  poi: String
}

impl PoI {
  pub fn new(poi: String) -> PoI {
    PoI {
      poi: poi
    }
  }

  pub fn set_poi(&mut self, poi: String) {
    self.poi = poi;
  }

  pub fn with_poi(mut self, poi: String) -> PoI {
    self.poi = poi;
    self
  }

  pub fn poi(&self) -> &String {
    &self.poi
  }


}



