/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PostTxResponse {
  /// Hash of a signed transaction
  #[serde(rename = "tx_hash")]
  tx_hash: ::models::EncodedHash
}

impl PostTxResponse {
  pub fn new(tx_hash: ::models::EncodedHash) -> PostTxResponse {
    PostTxResponse {
      tx_hash: tx_hash
    }
  }

  pub fn set_tx_hash(&mut self, tx_hash: ::models::EncodedHash) {
    self.tx_hash = tx_hash;
  }

  pub fn with_tx_hash(mut self, tx_hash: ::models::EncodedHash) -> PostTxResponse {
    self.tx_hash = tx_hash;
    self
  }

  pub fn tx_hash(&self) -> &::models::EncodedHash {
    &self.tx_hash
  }


}



