/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Protocol {
  #[serde(rename = "version")]
  version: i64,
  #[serde(rename = "effective_at_height")]
  effective_at_height: i64
}

impl Protocol {
  pub fn new(version: i64, effective_at_height: i64) -> Protocol {
    Protocol {
      version: version,
      effective_at_height: effective_at_height
    }
  }

  pub fn set_version(&mut self, version: i64) {
    self.version = version;
  }

  pub fn with_version(mut self, version: i64) -> Protocol {
    self.version = version;
    self
  }

  pub fn version(&self) -> &i64 {
    &self.version
  }


  pub fn set_effective_at_height(&mut self, effective_at_height: i64) {
    self.effective_at_height = effective_at_height;
  }

  pub fn with_effective_at_height(mut self, effective_at_height: i64) -> Protocol {
    self.effective_at_height = effective_at_height;
    self
  }

  pub fn effective_at_height(&self) -> &i64 {
    &self.effective_at_height
  }


}



