/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SophiaJsonData {
  #[serde(rename = "data")]
  data: Value
}

impl SophiaJsonData {
  pub fn new(data: Value) -> SophiaJsonData {
    SophiaJsonData {
      data: data
    }
  }

  pub fn set_data(&mut self, data: Value) {
    self.data = data;
  }

  pub fn with_data(mut self, data: Value) -> SophiaJsonData {
    self.data = data;
    self
  }

  pub fn data(&self) -> &Value {
    &self.data
  }


}



