/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SpendTxJson {
  #[serde(rename = "recipient_id")]
  recipient_id: ::models::EncodedHash,
  #[serde(rename = "amount")]
  amount: i64,
  #[serde(rename = "fee")]
  fee: i64,
  #[serde(rename = "ttl")]
  ttl: Option<i64>,
  #[serde(rename = "sender_id")]
  sender_id: ::models::EncodedHash,
  #[serde(rename = "nonce")]
  nonce: Option<i64>,
  #[serde(rename = "payload")]
  payload: String,
  #[serde(rename = "version")]
  version: i64,
  #[serde(rename = "type")]
  _type: String
}

impl SpendTxJson {
  pub fn new(recipient_id: ::models::EncodedHash, amount: i64, fee: i64, sender_id: ::models::EncodedHash, payload: String, version: i64, _type: String) -> SpendTxJson {
    SpendTxJson {
      recipient_id: recipient_id,
      amount: amount,
      fee: fee,
      ttl: None,
      sender_id: sender_id,
      nonce: None,
      payload: payload,
      version: version,
      _type: _type
    }
  }

  pub fn set_recipient_id(&mut self, recipient_id: ::models::EncodedHash) {
    self.recipient_id = recipient_id;
  }

  pub fn with_recipient_id(mut self, recipient_id: ::models::EncodedHash) -> SpendTxJson {
    self.recipient_id = recipient_id;
    self
  }

  pub fn recipient_id(&self) -> &::models::EncodedHash {
    &self.recipient_id
  }


  pub fn set_amount(&mut self, amount: i64) {
    self.amount = amount;
  }

  pub fn with_amount(mut self, amount: i64) -> SpendTxJson {
    self.amount = amount;
    self
  }

  pub fn amount(&self) -> &i64 {
    &self.amount
  }


  pub fn set_fee(&mut self, fee: i64) {
    self.fee = fee;
  }

  pub fn with_fee(mut self, fee: i64) -> SpendTxJson {
    self.fee = fee;
    self
  }

  pub fn fee(&self) -> &i64 {
    &self.fee
  }


  pub fn set_ttl(&mut self, ttl: i64) {
    self.ttl = Some(ttl);
  }

  pub fn with_ttl(mut self, ttl: i64) -> SpendTxJson {
    self.ttl = Some(ttl);
    self
  }

  pub fn ttl(&self) -> Option<&i64> {
    self.ttl.as_ref()
  }

  pub fn reset_ttl(&mut self) {
    self.ttl = None;
  }

  pub fn set_sender_id(&mut self, sender_id: ::models::EncodedHash) {
    self.sender_id = sender_id;
  }

  pub fn with_sender_id(mut self, sender_id: ::models::EncodedHash) -> SpendTxJson {
    self.sender_id = sender_id;
    self
  }

  pub fn sender_id(&self) -> &::models::EncodedHash {
    &self.sender_id
  }


  pub fn set_nonce(&mut self, nonce: i64) {
    self.nonce = Some(nonce);
  }

  pub fn with_nonce(mut self, nonce: i64) -> SpendTxJson {
    self.nonce = Some(nonce);
    self
  }

  pub fn nonce(&self) -> Option<&i64> {
    self.nonce.as_ref()
  }

  pub fn reset_nonce(&mut self) {
    self.nonce = None;
  }

  pub fn set_payload(&mut self, payload: String) {
    self.payload = payload;
  }

  pub fn with_payload(mut self, payload: String) -> SpendTxJson {
    self.payload = payload;
    self
  }

  pub fn payload(&self) -> &String {
    &self.payload
  }


  pub fn set_version(&mut self, version: i64) {
    self.version = version;
  }

  pub fn with_version(mut self, version: i64) -> SpendTxJson {
    self.version = version;
    self
  }

  pub fn version(&self) -> &i64 {
    &self.version
  }


  pub fn set__type(&mut self, _type: String) {
    self._type = _type;
  }

  pub fn with__type(mut self, _type: String) -> SpendTxJson {
    self._type = _type;
    self
  }

  pub fn _type(&self) -> &String {
    &self._type
  }


}



