/* 
 * Aeternity Epoch
 *
 * This is the [Aeternity](https://www.aeternity.com/) Epoch API.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: apiteam@aeternity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Ttl {
  #[serde(rename = "type")]
  _type: String,
  #[serde(rename = "value")]
  value: i64
}

impl Ttl {
  pub fn new(_type: String, value: i64) -> Ttl {
    Ttl {
      _type: _type,
      value: value
    }
  }

  pub fn set__type(&mut self, _type: String) {
    self._type = _type;
  }

  pub fn with__type(mut self, _type: String) -> Ttl {
    self._type = _type;
    self
  }

  pub fn _type(&self) -> &String {
    &self._type
  }


  pub fn set_value(&mut self, value: i64) {
    self.value = value;
  }

  pub fn with_value(mut self, value: i64) -> Ttl {
    self.value = value;
    self
  }

  pub fn value(&self) -> &i64 {
    &self.value
  }


}



